language: php

sudo: required

php:
  - 7.0
env:
  - DB=mysql

before_script:
  - composer install
  # - mysql -e 'CREATE DATABASE travis;'
  - mysql -u root travis < travis.sql
  - nohup php -S localhost:8888 &
  - telnet 127.0.0.1 80

script:
  - cd application/tests
  - phpunit
