language: php

addons:
  hosts:
  - travis.test
  
php:
  - 7.0
env:
  - DB=mysql

before_script:
  - composer install
  # - mysql -e 'CREATE DATABASE travis;'
  - mysql -u root travis < travis.sql

script:
  - cd application/tests
  - phpunit
