language: php

sudo: required

php:
  - 7.0
env:
  - DB=mysql

before_script:
  - composer install
  # - mysql -e 'CREATE DATABASE travis;'
  - mysql -u root travis < travis.sql

script:
  - nohup php -S localhost:80 &
  - cd application/tests
  - phpunit
