language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - DB=mysql
  - DB=pdo/mysql

before_script:
  - composer install
  - mysql -e 'CREATE DATABASE travis;'
  - mysql -u root travis < travis.sql

script:
  - cd application/tests
  - phpunit
